#!/bin/bash
STRING="Setup of the RasPi Camera"
echo $STRING
# install reaquired packages
sudo apt-get install libjpeg8-dev imagemagick libv4l-dev
# new link so that videodev.h is found by mjpg-streamer
sudo -ln -s /usr/include/linux/videodev2.h /usr/include/linux/videodev.h
# download MJPG-Streamer and unzip
wget http://tredoryswebsite.de/wp-content/uploads/2013/11/mjpg-streamer-code-182.zip
unzip mjpg-streamer-code-182.zip
# create program files 
cd mjpg-streamer-code-182/mjpg-streamer
make mjpg_streamer input_file.so output_http.so
# install program files
sudo cp mjpg_streamer /usr/local/bin
sudo cp output_http.so input_file.so /usr/local/lib
sudo cp -R www /usr/local/www
# remove temporary folder
cd ~
rm -rf mjpg-streamer-code-182
rm mjpg-streamer-code-182.zip

